name: OrderGetterR package

on:
    push:
      branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt pyinstaller
          echo $PYLIB_DIR

      - name: archiving(macos)
        if: runner.os != 'Windows'
        run: |
          pyinstaller --onefile --exclude pandas --exclude numpy --noupx --add-data ${{env.Python3_ROOT_DIR}}/lib/python3.10/site-packages/rakuten_ws/wsdl/orderapi.wsdl:rakuten_ws/wsdl src/OrderGetterR.py
          chmod a+x dist/OrderGetterR
        
      - name: archiving(Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --exclude pandas --exclude numpy --noupx --add-data "${{env.Python3_ROOT_DIR}}\lib\site-packages\rakuten_ws\wsdl\orderapi.wsdl;rakuten_ws\wsdl" src\OrderGetterR.py
        
      - name: copy files
        run: |
          cp readme.txt dist/
          cp setting.ini dist/
          cp input.txt dist/
          cp input_rpay.txt dist/
          cp input_type1.txt dist/
          mv dist OrderGetterR-${{runner.os}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OrderGetterR-${{ runner.os }}
          path: |
            OrderGetterR-${{runner.os}}
